title: "minosoft"
description: "Pascal PINCHAURET-LAMOTHE Â· Consultant en Informatique Â· GenÃ¨ve Â· Canton de Vaud Â· Suisse"
baseurl: "/minosoft-web-site"  # nom de ton repo
#baseurl: "" # Ã  utiliser si ton site n'est pas Ã  la racine
#url: "https://ton-nom.github.io" # Ã  adapter si tu hÃ©berges ailleurs
url: "https://minosoft-fr.github.io"

# ğŸ“ Version
version:
  major: 1
  minor: 0
  patch: 0
  build: 20

# ğŸ“ Last update (git)
last_update: "2025-08-07 14:07:05 +0200"

# ğŸ–¼ï¸ ThÃ¨me distant (Architect)
remote_theme: pages-themes/architect@v0.2.0
theme: null

# ğŸ‘¤ Auteur
author:
  name: "Pascal PINCHAURET-LAMOTHE"
  email: "ton.email@example.com"

# ğŸ“ Dossiers exclus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

# ğŸ“¦ Plugins utilisÃ©s
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ğŸ” Options SEO
seo:
  type: "Person"
  name: "Pascal PINCHAURET-LAMOTHE"
  social:
    name: "minosoft"
    links:
      - "https://linkedin.com/in/pinchoonet"
      - "https://github.com/minosoft-2048"

# ğŸ—‚ï¸ Navigation dynamique (si tu as _data/navigation.yml)
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
